name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode Sync
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.1.0
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
