name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *" # Runs daily at 8:00 AM IST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github_token: ${{ github.token }}
          leetcode_csrf_token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
